FOURSQUARE_CLIENT_ID = 'I1ATRYBZLDI0EDEZFGC1BADYRVRMLOUMB3GNNS2WNB1U4LHE'
FOURSQUARE_SECRET = 'BCZOYVOBG2GOBTR2NTSNX3QVAVWDDJN2AZ2XIIEPGJQRV1TK'
FS_CLIENT = Foursquare2::Client.new(:client_id => FOURSQUARE_CLIENT_ID, :client_secret => FOURSQUARE_SECRET)

